# Setup
title:            The Dogeington Post
tagline:          'Bad content or your money back!'
description:      'Made by <a href="https://mastodon.gamedev.place/@Doge4ever05" target="_blank">@doge4ever05</a>.'
url:              http://doge4ever05.github.io
baseurl:          
paginate:         5

# About and contact
author:
  name:           'Aaron Pruitt'
  url:            https://mastodon.gamedev.place/@Doge4ever05

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
