# Setup
title:            The Dogeington Post
tagline:          'Bad content or your money back!'
description:      'Made by <a href="https://mastodon.gamedev.place/@Doge4ever05" target="_blank">@doge4ever05</a>.'
url:              https://hyde.getpoole.com
baseurl:          'http://doge4ever05.github.io/'
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
